//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.PortableServices.Advisors {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdvisorDto", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.Dto")]
    public partial class AdvisorDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FirstNameField;
        
        private int IdField;
        
        private string IdentificationField;
        
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identification {
            get {
                return this.IdentificationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationField, value) != true)) {
                    this.IdentificationField = value;
                    this.RaisePropertyChanged("Identification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="octo.advisors.service", ConfigurationName="Advisors.WCFAdvisorService")]
    public interface WCFAdvisorService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.advisors.service/WCFAdvisorService/GetCurrentAdvisor", ReplyAction="octo.advisors.service/WCFAdvisorService/GetCurrentAdvisorResponse")]
        System.IAsyncResult BeginGetCurrentAdvisor(System.AsyncCallback callback, object asyncState);
        
        CloudyBank.PortableServices.Advisors.AdvisorDto EndGetCurrentAdvisor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.advisors.service/WCFAdvisorService/GetAdvisorById", ReplyAction="octo.advisors.service/WCFAdvisorService/GetAdvisorByIdResponse")]
        System.IAsyncResult BeginGetAdvisorById(int id, System.AsyncCallback callback, object asyncState);
        
        CloudyBank.PortableServices.Advisors.AdvisorDto EndGetAdvisorById(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFAdvisorServiceChannel : CloudyBank.PortableServices.Advisors.WCFAdvisorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentAdvisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentAdvisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudyBank.PortableServices.Advisors.AdvisorDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudyBank.PortableServices.Advisors.AdvisorDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAdvisorByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAdvisorByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudyBank.PortableServices.Advisors.AdvisorDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudyBank.PortableServices.Advisors.AdvisorDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAdvisorServiceClient : System.ServiceModel.ClientBase<CloudyBank.PortableServices.Advisors.WCFAdvisorService>, CloudyBank.PortableServices.Advisors.WCFAdvisorService {
        
        private BeginOperationDelegate onBeginGetCurrentAdvisorDelegate;
        
        private EndOperationDelegate onEndGetCurrentAdvisorDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentAdvisorCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAdvisorByIdDelegate;
        
        private EndOperationDelegate onEndGetAdvisorByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetAdvisorByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFAdvisorServiceClient() {
        }
        
        public WCFAdvisorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAdvisorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAdvisorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAdvisorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetCurrentAdvisorCompletedEventArgs> GetCurrentAdvisorCompleted;
        
        public event System.EventHandler<GetAdvisorByIdCompletedEventArgs> GetAdvisorByIdCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Advisors.WCFAdvisorService.BeginGetCurrentAdvisor(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentAdvisor(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudyBank.PortableServices.Advisors.AdvisorDto CloudyBank.PortableServices.Advisors.WCFAdvisorService.EndGetCurrentAdvisor(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentAdvisor(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentAdvisor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CloudyBank.PortableServices.Advisors.WCFAdvisorService)(this)).BeginGetCurrentAdvisor(callback, asyncState);
        }
        
        private object[] OnEndGetCurrentAdvisor(System.IAsyncResult result) {
            CloudyBank.PortableServices.Advisors.AdvisorDto retVal = ((CloudyBank.PortableServices.Advisors.WCFAdvisorService)(this)).EndGetCurrentAdvisor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentAdvisorCompleted(object state) {
            if ((this.GetCurrentAdvisorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentAdvisorCompleted(this, new GetCurrentAdvisorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentAdvisorAsync() {
            this.GetCurrentAdvisorAsync(null);
        }
        
        public void GetCurrentAdvisorAsync(object userState) {
            if ((this.onBeginGetCurrentAdvisorDelegate == null)) {
                this.onBeginGetCurrentAdvisorDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentAdvisor);
            }
            if ((this.onEndGetCurrentAdvisorDelegate == null)) {
                this.onEndGetCurrentAdvisorDelegate = new EndOperationDelegate(this.OnEndGetCurrentAdvisor);
            }
            if ((this.onGetCurrentAdvisorCompletedDelegate == null)) {
                this.onGetCurrentAdvisorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentAdvisorCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentAdvisorDelegate, null, this.onEndGetCurrentAdvisorDelegate, this.onGetCurrentAdvisorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Advisors.WCFAdvisorService.BeginGetAdvisorById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAdvisorById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudyBank.PortableServices.Advisors.AdvisorDto CloudyBank.PortableServices.Advisors.WCFAdvisorService.EndGetAdvisorById(System.IAsyncResult result) {
            return base.Channel.EndGetAdvisorById(result);
        }
        
        private System.IAsyncResult OnBeginGetAdvisorById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.Advisors.WCFAdvisorService)(this)).BeginGetAdvisorById(id, callback, asyncState);
        }
        
        private object[] OnEndGetAdvisorById(System.IAsyncResult result) {
            CloudyBank.PortableServices.Advisors.AdvisorDto retVal = ((CloudyBank.PortableServices.Advisors.WCFAdvisorService)(this)).EndGetAdvisorById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAdvisorByIdCompleted(object state) {
            if ((this.GetAdvisorByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAdvisorByIdCompleted(this, new GetAdvisorByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAdvisorByIdAsync(int id) {
            this.GetAdvisorByIdAsync(id, null);
        }
        
        public void GetAdvisorByIdAsync(int id, object userState) {
            if ((this.onBeginGetAdvisorByIdDelegate == null)) {
                this.onBeginGetAdvisorByIdDelegate = new BeginOperationDelegate(this.OnBeginGetAdvisorById);
            }
            if ((this.onEndGetAdvisorByIdDelegate == null)) {
                this.onEndGetAdvisorByIdDelegate = new EndOperationDelegate(this.OnEndGetAdvisorById);
            }
            if ((this.onGetAdvisorByIdCompletedDelegate == null)) {
                this.onGetAdvisorByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAdvisorByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetAdvisorByIdDelegate, new object[] {
                        id}, this.onEndGetAdvisorByIdDelegate, this.onGetAdvisorByIdCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudyBank.PortableServices.Advisors.WCFAdvisorService CreateChannel() {
            return new WCFAdvisorServiceClientChannel(this);
        }
        
        private class WCFAdvisorServiceClientChannel : ChannelBase<CloudyBank.PortableServices.Advisors.WCFAdvisorService>, CloudyBank.PortableServices.Advisors.WCFAdvisorService {
            
            public WCFAdvisorServiceClientChannel(System.ServiceModel.ClientBase<CloudyBank.PortableServices.Advisors.WCFAdvisorService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCurrentAdvisor(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentAdvisor", _args, callback, asyncState);
                return _result;
            }
            
            public CloudyBank.PortableServices.Advisors.AdvisorDto EndGetCurrentAdvisor(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudyBank.PortableServices.Advisors.AdvisorDto _result = ((CloudyBank.PortableServices.Advisors.AdvisorDto)(base.EndInvoke("GetCurrentAdvisor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAdvisorById(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetAdvisorById", _args, callback, asyncState);
                return _result;
            }
            
            public CloudyBank.PortableServices.Advisors.AdvisorDto EndGetAdvisorById(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudyBank.PortableServices.Advisors.AdvisorDto _result = ((CloudyBank.PortableServices.Advisors.AdvisorDto)(base.EndInvoke("GetAdvisorById", _args, result)));
                return _result;
            }
        }
    }
}
