//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.PortableServices.Users {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentityDto", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.Dto")]
    public partial class UserIdentityDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private int IdField;
        
        private string IdentificationField;
        
        private CloudyBank.PortableServices.Users.UserType UserTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identification {
            get {
                return this.IdentificationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationField, value) != true)) {
                    this.IdentificationField = value;
                    this.RaisePropertyChanged("Identification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CloudyBank.PortableServices.Users.UserType UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.CoreDomain.Security")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoType = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndividualCustomer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorporateCustomer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Advisor = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrator = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="octo.users.service", ConfigurationName="Users.WCFUserService")]
    public interface WCFUserService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.users.service/WCFUserService/GetCurrentUser", ReplyAction="octo.users.service/WCFUserService/GetCurrentUserResponse")]
        System.IAsyncResult BeginGetCurrentUser(System.AsyncCallback callback, object asyncState);
        
        CloudyBank.PortableServices.Users.UserIdentityDto EndGetCurrentUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.users.service/WCFUserService/LoginCookie", ReplyAction="octo.users.service/WCFUserService/LoginCookieResponse")]
        System.IAsyncResult BeginLoginCookie(string login, string password, System.AsyncCallback callback, object asyncState);
        
        string EndLoginCookie(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.users.service/WCFUserService/Login", ReplyAction="octo.users.service/WCFUserService/LoginResponse")]
        System.IAsyncResult BeginLogin(string login, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.users.service/WCFUserService/LoginGetID", ReplyAction="octo.users.service/WCFUserService/LoginGetIDResponse")]
        System.IAsyncResult BeginLoginGetID(string login, string password, System.AsyncCallback callback, object asyncState);
        
        int EndLoginGetID(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.users.service/WCFUserService/Logout", ReplyAction="octo.users.service/WCFUserService/LogoutResponse")]
        System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState);
        
        void EndLogout(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFUserServiceChannel : CloudyBank.PortableServices.Users.WCFUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudyBank.PortableServices.Users.UserIdentityDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudyBank.PortableServices.Users.UserIdentityDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCookieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCookieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginGetIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginGetIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFUserServiceClient : System.ServiceModel.ClientBase<CloudyBank.PortableServices.Users.WCFUserService>, CloudyBank.PortableServices.Users.WCFUserService {
        
        private BeginOperationDelegate onBeginGetCurrentUserDelegate;
        
        private EndOperationDelegate onEndGetCurrentUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginCookieDelegate;
        
        private EndOperationDelegate onEndLoginCookieDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCookieCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginGetIDDelegate;
        
        private EndOperationDelegate onEndLoginGetIDDelegate;
        
        private System.Threading.SendOrPostCallback onLoginGetIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogoutDelegate;
        
        private EndOperationDelegate onEndLogoutDelegate;
        
        private System.Threading.SendOrPostCallback onLogoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFUserServiceClient() {
        }
        
        public WCFUserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFUserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFUserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFUserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetCurrentUserCompletedEventArgs> GetCurrentUserCompleted;
        
        public event System.EventHandler<LoginCookieCompletedEventArgs> LoginCookieCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<LoginGetIDCompletedEventArgs> LoginGetIDCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LogoutCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Users.WCFUserService.BeginGetCurrentUser(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentUser(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudyBank.PortableServices.Users.UserIdentityDto CloudyBank.PortableServices.Users.WCFUserService.EndGetCurrentUser(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentUser(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CloudyBank.PortableServices.Users.WCFUserService)(this)).BeginGetCurrentUser(callback, asyncState);
        }
        
        private object[] OnEndGetCurrentUser(System.IAsyncResult result) {
            CloudyBank.PortableServices.Users.UserIdentityDto retVal = ((CloudyBank.PortableServices.Users.WCFUserService)(this)).EndGetCurrentUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentUserCompleted(object state) {
            if ((this.GetCurrentUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentUserCompleted(this, new GetCurrentUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentUserAsync() {
            this.GetCurrentUserAsync(null);
        }
        
        public void GetCurrentUserAsync(object userState) {
            if ((this.onBeginGetCurrentUserDelegate == null)) {
                this.onBeginGetCurrentUserDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentUser);
            }
            if ((this.onEndGetCurrentUserDelegate == null)) {
                this.onEndGetCurrentUserDelegate = new EndOperationDelegate(this.OnEndGetCurrentUser);
            }
            if ((this.onGetCurrentUserCompletedDelegate == null)) {
                this.onGetCurrentUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentUserDelegate, null, this.onEndGetCurrentUserDelegate, this.onGetCurrentUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Users.WCFUserService.BeginLoginCookie(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginCookie(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string CloudyBank.PortableServices.Users.WCFUserService.EndLoginCookie(System.IAsyncResult result) {
            return base.Channel.EndLoginCookie(result);
        }
        
        private System.IAsyncResult OnBeginLoginCookie(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((CloudyBank.PortableServices.Users.WCFUserService)(this)).BeginLoginCookie(login, password, callback, asyncState);
        }
        
        private object[] OnEndLoginCookie(System.IAsyncResult result) {
            string retVal = ((CloudyBank.PortableServices.Users.WCFUserService)(this)).EndLoginCookie(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCookieCompleted(object state) {
            if ((this.LoginCookieCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCookieCompleted(this, new LoginCookieCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginCookieAsync(string login, string password) {
            this.LoginCookieAsync(login, password, null);
        }
        
        public void LoginCookieAsync(string login, string password, object userState) {
            if ((this.onBeginLoginCookieDelegate == null)) {
                this.onBeginLoginCookieDelegate = new BeginOperationDelegate(this.OnBeginLoginCookie);
            }
            if ((this.onEndLoginCookieDelegate == null)) {
                this.onEndLoginCookieDelegate = new EndOperationDelegate(this.OnEndLoginCookie);
            }
            if ((this.onLoginCookieCompletedDelegate == null)) {
                this.onLoginCookieCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCookieCompleted);
            }
            base.InvokeAsync(this.onBeginLoginCookieDelegate, new object[] {
                        login,
                        password}, this.onEndLoginCookieDelegate, this.onLoginCookieCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Users.WCFUserService.BeginLogin(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool CloudyBank.PortableServices.Users.WCFUserService.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((CloudyBank.PortableServices.Users.WCFUserService)(this)).BeginLogin(login, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            bool retVal = ((CloudyBank.PortableServices.Users.WCFUserService)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string login, string password) {
            this.LoginAsync(login, password, null);
        }
        
        public void LoginAsync(string login, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        login,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Users.WCFUserService.BeginLoginGetID(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginGetID(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CloudyBank.PortableServices.Users.WCFUserService.EndLoginGetID(System.IAsyncResult result) {
            return base.Channel.EndLoginGetID(result);
        }
        
        private System.IAsyncResult OnBeginLoginGetID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((CloudyBank.PortableServices.Users.WCFUserService)(this)).BeginLoginGetID(login, password, callback, asyncState);
        }
        
        private object[] OnEndLoginGetID(System.IAsyncResult result) {
            int retVal = ((CloudyBank.PortableServices.Users.WCFUserService)(this)).EndLoginGetID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginGetIDCompleted(object state) {
            if ((this.LoginGetIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginGetIDCompleted(this, new LoginGetIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginGetIDAsync(string login, string password) {
            this.LoginGetIDAsync(login, password, null);
        }
        
        public void LoginGetIDAsync(string login, string password, object userState) {
            if ((this.onBeginLoginGetIDDelegate == null)) {
                this.onBeginLoginGetIDDelegate = new BeginOperationDelegate(this.OnBeginLoginGetID);
            }
            if ((this.onEndLoginGetIDDelegate == null)) {
                this.onEndLoginGetIDDelegate = new EndOperationDelegate(this.OnEndLoginGetID);
            }
            if ((this.onLoginGetIDCompletedDelegate == null)) {
                this.onLoginGetIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginGetIDCompleted);
            }
            base.InvokeAsync(this.onBeginLoginGetIDDelegate, new object[] {
                        login,
                        password}, this.onEndLoginGetIDDelegate, this.onLoginGetIDCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Users.WCFUserService.BeginLogout(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogout(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CloudyBank.PortableServices.Users.WCFUserService.EndLogout(System.IAsyncResult result) {
            base.Channel.EndLogout(result);
        }
        
        private System.IAsyncResult OnBeginLogout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CloudyBank.PortableServices.Users.WCFUserService)(this)).BeginLogout(callback, asyncState);
        }
        
        private object[] OnEndLogout(System.IAsyncResult result) {
            ((CloudyBank.PortableServices.Users.WCFUserService)(this)).EndLogout(result);
            return null;
        }
        
        private void OnLogoutCompleted(object state) {
            if ((this.LogoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        public void LogoutAsync(object userState) {
            if ((this.onBeginLogoutDelegate == null)) {
                this.onBeginLogoutDelegate = new BeginOperationDelegate(this.OnBeginLogout);
            }
            if ((this.onEndLogoutDelegate == null)) {
                this.onEndLogoutDelegate = new EndOperationDelegate(this.OnEndLogout);
            }
            if ((this.onLogoutCompletedDelegate == null)) {
                this.onLogoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogoutCompleted);
            }
            base.InvokeAsync(this.onBeginLogoutDelegate, null, this.onEndLogoutDelegate, this.onLogoutCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudyBank.PortableServices.Users.WCFUserService CreateChannel() {
            return new WCFUserServiceClientChannel(this);
        }
        
        private class WCFUserServiceClientChannel : ChannelBase<CloudyBank.PortableServices.Users.WCFUserService>, CloudyBank.PortableServices.Users.WCFUserService {
            
            public WCFUserServiceClientChannel(System.ServiceModel.ClientBase<CloudyBank.PortableServices.Users.WCFUserService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetCurrentUser(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentUser", _args, callback, asyncState);
                return _result;
            }
            
            public CloudyBank.PortableServices.Users.UserIdentityDto EndGetCurrentUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudyBank.PortableServices.Users.UserIdentityDto _result = ((CloudyBank.PortableServices.Users.UserIdentityDto)(base.EndInvoke("GetCurrentUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoginCookie(string login, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("LoginCookie", _args, callback, asyncState);
                return _result;
            }
            
            public string EndLoginCookie(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("LoginCookie", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogin(string login, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoginGetID(string login, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("LoginGetID", _args, callback, asyncState);
                return _result;
            }
            
            public int EndLoginGetID(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("LoginGetID", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Logout", _args, callback, asyncState);
                return _result;
            }
            
            public void EndLogout(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Logout", _args, result);
            }
        }
    }
}
