//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.PortableServices.Customers {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.Dto")]
    public partial class CustomerDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime BirthDateField;
        
        private string CodeField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string IdentificationField;
        
        private string LastNameField;
        
        private string PhoneNumberField;
        
        private CloudyBank.PortableServices.Customers.FamilySituation SituationField;
        
        private string TitleField;
        
        private CloudyBank.PortableServices.Customers.UserType TypeField;
        
        private string UserCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identification {
            get {
                return this.IdentificationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationField, value) != true)) {
                    this.IdentificationField = value;
                    this.RaisePropertyChanged("Identification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CloudyBank.PortableServices.Customers.FamilySituation Situation {
            get {
                return this.SituationField;
            }
            set {
                if ((this.SituationField.Equals(value) != true)) {
                    this.SituationField = value;
                    this.RaisePropertyChanged("Situation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CloudyBank.PortableServices.Customers.UserType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FamilySituation", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.CoreDomain.Customers")]
    public enum FamilySituation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InCouple = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Maried = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.CoreDomain.Security")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoType = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndividualCustomer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorporateCustomer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Advisor = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Administrator = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="octo.customers.service", ConfigurationName="Customers.WCFCustomersService")]
    public interface WCFCustomersService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.customers.service/WCFCustomersService/SaveCustomerDto", ReplyAction="octo.customers.service/WCFCustomersService/SaveCustomerDtoResponse")]
        System.IAsyncResult BeginSaveCustomerDto(CloudyBank.PortableServices.Customers.CustomerDto customerDto, System.AsyncCallback callback, object asyncState);
        
        void EndSaveCustomerDto(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.customers.service/WCFCustomersService/GetCustomersForAdvisor", ReplyAction="octo.customers.service/WCFCustomersService/GetCustomersForAdvisorResponse")]
        System.IAsyncResult BeginGetCustomersForAdvisor(int advisorID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto> EndGetCustomersForAdvisor(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.customers.service/WCFCustomersService/GetCurrentCustomer", ReplyAction="octo.customers.service/WCFCustomersService/GetCurrentCustomerResponse")]
        System.IAsyncResult BeginGetCurrentCustomer(System.AsyncCallback callback, object asyncState);
        
        CloudyBank.PortableServices.Customers.CustomerDto EndGetCurrentCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.customers.service/WCFCustomersService/GetCustomerByID", ReplyAction="octo.customers.service/WCFCustomersService/GetCustomerByIDResponse")]
        System.IAsyncResult BeginGetCustomerByID(int id, System.AsyncCallback callback, object asyncState);
        
        CloudyBank.PortableServices.Customers.CustomerDto EndGetCustomerByID(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFCustomersServiceChannel : CloudyBank.PortableServices.Customers.WCFCustomersService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomersForAdvisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomersForAdvisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudyBank.PortableServices.Customers.CustomerDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudyBank.PortableServices.Customers.CustomerDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCustomerByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCustomerByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudyBank.PortableServices.Customers.CustomerDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudyBank.PortableServices.Customers.CustomerDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCustomersServiceClient : System.ServiceModel.ClientBase<CloudyBank.PortableServices.Customers.WCFCustomersService>, CloudyBank.PortableServices.Customers.WCFCustomersService {
        
        private BeginOperationDelegate onBeginSaveCustomerDtoDelegate;
        
        private EndOperationDelegate onEndSaveCustomerDtoDelegate;
        
        private System.Threading.SendOrPostCallback onSaveCustomerDtoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCustomersForAdvisorDelegate;
        
        private EndOperationDelegate onEndGetCustomersForAdvisorDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomersForAdvisorCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCurrentCustomerDelegate;
        
        private EndOperationDelegate onEndGetCurrentCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCustomerByIDDelegate;
        
        private EndOperationDelegate onEndGetCustomerByIDDelegate;
        
        private System.Threading.SendOrPostCallback onGetCustomerByIDCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFCustomersServiceClient() {
        }
        
        public WCFCustomersServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFCustomersServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCustomersServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCustomersServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveCustomerDtoCompleted;
        
        public event System.EventHandler<GetCustomersForAdvisorCompletedEventArgs> GetCustomersForAdvisorCompleted;
        
        public event System.EventHandler<GetCurrentCustomerCompletedEventArgs> GetCurrentCustomerCompleted;
        
        public event System.EventHandler<GetCustomerByIDCompletedEventArgs> GetCustomerByIDCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Customers.WCFCustomersService.BeginSaveCustomerDto(CloudyBank.PortableServices.Customers.CustomerDto customerDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveCustomerDto(customerDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CloudyBank.PortableServices.Customers.WCFCustomersService.EndSaveCustomerDto(System.IAsyncResult result) {
            base.Channel.EndSaveCustomerDto(result);
        }
        
        private System.IAsyncResult OnBeginSaveCustomerDto(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CloudyBank.PortableServices.Customers.CustomerDto customerDto = ((CloudyBank.PortableServices.Customers.CustomerDto)(inValues[0]));
            return ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).BeginSaveCustomerDto(customerDto, callback, asyncState);
        }
        
        private object[] OnEndSaveCustomerDto(System.IAsyncResult result) {
            ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).EndSaveCustomerDto(result);
            return null;
        }
        
        private void OnSaveCustomerDtoCompleted(object state) {
            if ((this.SaveCustomerDtoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveCustomerDtoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveCustomerDtoAsync(CloudyBank.PortableServices.Customers.CustomerDto customerDto) {
            this.SaveCustomerDtoAsync(customerDto, null);
        }
        
        public void SaveCustomerDtoAsync(CloudyBank.PortableServices.Customers.CustomerDto customerDto, object userState) {
            if ((this.onBeginSaveCustomerDtoDelegate == null)) {
                this.onBeginSaveCustomerDtoDelegate = new BeginOperationDelegate(this.OnBeginSaveCustomerDto);
            }
            if ((this.onEndSaveCustomerDtoDelegate == null)) {
                this.onEndSaveCustomerDtoDelegate = new EndOperationDelegate(this.OnEndSaveCustomerDto);
            }
            if ((this.onSaveCustomerDtoCompletedDelegate == null)) {
                this.onSaveCustomerDtoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveCustomerDtoCompleted);
            }
            base.InvokeAsync(this.onBeginSaveCustomerDtoDelegate, new object[] {
                        customerDto}, this.onEndSaveCustomerDtoDelegate, this.onSaveCustomerDtoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Customers.WCFCustomersService.BeginGetCustomersForAdvisor(int advisorID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomersForAdvisor(advisorID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto> CloudyBank.PortableServices.Customers.WCFCustomersService.EndGetCustomersForAdvisor(System.IAsyncResult result) {
            return base.Channel.EndGetCustomersForAdvisor(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomersForAdvisor(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int advisorID = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).BeginGetCustomersForAdvisor(advisorID, callback, asyncState);
        }
        
        private object[] OnEndGetCustomersForAdvisor(System.IAsyncResult result) {
            System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto> retVal = ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).EndGetCustomersForAdvisor(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomersForAdvisorCompleted(object state) {
            if ((this.GetCustomersForAdvisorCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomersForAdvisorCompleted(this, new GetCustomersForAdvisorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomersForAdvisorAsync(int advisorID) {
            this.GetCustomersForAdvisorAsync(advisorID, null);
        }
        
        public void GetCustomersForAdvisorAsync(int advisorID, object userState) {
            if ((this.onBeginGetCustomersForAdvisorDelegate == null)) {
                this.onBeginGetCustomersForAdvisorDelegate = new BeginOperationDelegate(this.OnBeginGetCustomersForAdvisor);
            }
            if ((this.onEndGetCustomersForAdvisorDelegate == null)) {
                this.onEndGetCustomersForAdvisorDelegate = new EndOperationDelegate(this.OnEndGetCustomersForAdvisor);
            }
            if ((this.onGetCustomersForAdvisorCompletedDelegate == null)) {
                this.onGetCustomersForAdvisorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomersForAdvisorCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomersForAdvisorDelegate, new object[] {
                        advisorID}, this.onEndGetCustomersForAdvisorDelegate, this.onGetCustomersForAdvisorCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Customers.WCFCustomersService.BeginGetCurrentCustomer(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentCustomer(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudyBank.PortableServices.Customers.CustomerDto CloudyBank.PortableServices.Customers.WCFCustomersService.EndGetCurrentCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).BeginGetCurrentCustomer(callback, asyncState);
        }
        
        private object[] OnEndGetCurrentCustomer(System.IAsyncResult result) {
            CloudyBank.PortableServices.Customers.CustomerDto retVal = ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).EndGetCurrentCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentCustomerCompleted(object state) {
            if ((this.GetCurrentCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentCustomerCompleted(this, new GetCurrentCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentCustomerAsync() {
            this.GetCurrentCustomerAsync(null);
        }
        
        public void GetCurrentCustomerAsync(object userState) {
            if ((this.onBeginGetCurrentCustomerDelegate == null)) {
                this.onBeginGetCurrentCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentCustomer);
            }
            if ((this.onEndGetCurrentCustomerDelegate == null)) {
                this.onEndGetCurrentCustomerDelegate = new EndOperationDelegate(this.OnEndGetCurrentCustomer);
            }
            if ((this.onGetCurrentCustomerCompletedDelegate == null)) {
                this.onGetCurrentCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentCustomerDelegate, null, this.onEndGetCurrentCustomerDelegate, this.onGetCurrentCustomerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Customers.WCFCustomersService.BeginGetCustomerByID(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCustomerByID(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudyBank.PortableServices.Customers.CustomerDto CloudyBank.PortableServices.Customers.WCFCustomersService.EndGetCustomerByID(System.IAsyncResult result) {
            return base.Channel.EndGetCustomerByID(result);
        }
        
        private System.IAsyncResult OnBeginGetCustomerByID(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).BeginGetCustomerByID(id, callback, asyncState);
        }
        
        private object[] OnEndGetCustomerByID(System.IAsyncResult result) {
            CloudyBank.PortableServices.Customers.CustomerDto retVal = ((CloudyBank.PortableServices.Customers.WCFCustomersService)(this)).EndGetCustomerByID(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCustomerByIDCompleted(object state) {
            if ((this.GetCustomerByIDCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCustomerByIDCompleted(this, new GetCustomerByIDCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCustomerByIDAsync(int id) {
            this.GetCustomerByIDAsync(id, null);
        }
        
        public void GetCustomerByIDAsync(int id, object userState) {
            if ((this.onBeginGetCustomerByIDDelegate == null)) {
                this.onBeginGetCustomerByIDDelegate = new BeginOperationDelegate(this.OnBeginGetCustomerByID);
            }
            if ((this.onEndGetCustomerByIDDelegate == null)) {
                this.onEndGetCustomerByIDDelegate = new EndOperationDelegate(this.OnEndGetCustomerByID);
            }
            if ((this.onGetCustomerByIDCompletedDelegate == null)) {
                this.onGetCustomerByIDCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCustomerByIDCompleted);
            }
            base.InvokeAsync(this.onBeginGetCustomerByIDDelegate, new object[] {
                        id}, this.onEndGetCustomerByIDDelegate, this.onGetCustomerByIDCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudyBank.PortableServices.Customers.WCFCustomersService CreateChannel() {
            return new WCFCustomersServiceClientChannel(this);
        }
        
        private class WCFCustomersServiceClientChannel : ChannelBase<CloudyBank.PortableServices.Customers.WCFCustomersService>, CloudyBank.PortableServices.Customers.WCFCustomersService {
            
            public WCFCustomersServiceClientChannel(System.ServiceModel.ClientBase<CloudyBank.PortableServices.Customers.WCFCustomersService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSaveCustomerDto(CloudyBank.PortableServices.Customers.CustomerDto customerDto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerDto;
                System.IAsyncResult _result = base.BeginInvoke("SaveCustomerDto", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSaveCustomerDto(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("SaveCustomerDto", _args, result);
            }
            
            public System.IAsyncResult BeginGetCustomersForAdvisor(int advisorID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = advisorID;
                System.IAsyncResult _result = base.BeginInvoke("GetCustomersForAdvisor", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto> EndGetCustomersForAdvisor(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto> _result = ((System.Collections.Generic.List<CloudyBank.PortableServices.Customers.CustomerDto>)(base.EndInvoke("GetCustomersForAdvisor", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCurrentCustomer(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public CloudyBank.PortableServices.Customers.CustomerDto EndGetCurrentCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudyBank.PortableServices.Customers.CustomerDto _result = ((CloudyBank.PortableServices.Customers.CustomerDto)(base.EndInvoke("GetCurrentCustomer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCustomerByID(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetCustomerByID", _args, callback, asyncState);
                return _result;
            }
            
            public CloudyBank.PortableServices.Customers.CustomerDto EndGetCustomerByID(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudyBank.PortableServices.Customers.CustomerDto _result = ((CloudyBank.PortableServices.Customers.CustomerDto)(base.EndInvoke("GetCustomerByID", _args, result)));
                return _result;
            }
        }
    }
}
