//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.Web.Ria.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgencyPageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgencyPageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudyBank.Web.Ria.Resources.Pages.AgencyPageRes", typeof(AgencyPageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the branch stores.
        /// </summary>
        public static string Agencies {
            get {
                return ResourceManager.GetString("Agencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch address:.
        /// </summary>
        public static string BranchAddress {
            get {
                return ResourceManager.GetString("BranchAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing hour:.
        /// </summary>
        public static string CloseHour {
            get {
                return ResourceManager.GetString("CloseHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Vault.
        /// </summary>
        public static string ElectronicVault {
            get {
                return ResourceManager.GetString("ElectronicVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Agencies.
        /// </summary>
        public static string FindAgencies {
            get {
                return ResourceManager.GetString("FindAgencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Accounts Overview.
        /// </summary>
        public static string GenerateAccountsOverview {
            get {
                return ResourceManager.GetString("GenerateAccountsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Transfer.
        /// </summary>
        public static string MakeTransfer {
            get {
                return ResourceManager.GetString("MakeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New transaction.
        /// </summary>
        public static string NewTransaction {
            get {
                return ResourceManager.GetString("NewTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a branch store from the map to get detail information about the closing and openning.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hour:.
        /// </summary>
        public static string OpenHour {
            get {
                return ResourceManager.GetString("OpenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open new account.
        /// </summary>
        public static string OpenNewAccount {
            get {
                return ResourceManager.GetString("OpenNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print RIB.
        /// </summary>
        public static string PrintRIB {
            get {
                return ResourceManager.GetString("PrintRIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic vault.
        /// </summary>
        public static string Vault {
            get {
                return ResourceManager.GetString("Vault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the place to share documents with your bank. You can upload any documents as well as download the ones created for you by your bank, such as account overview.
        /// </summary>
        public static string VaultNote {
            get {
                return ResourceManager.GetString("VaultNote", resourceCulture);
            }
        }
    }
}
