//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.Web.Ria.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfilePageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfilePageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudyBank.Web.Ria.Resources.Pages.ProfilePageRes", typeof(ProfilePageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunity.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How the others do?.
        /// </summary>
        public static string CommunityDepenses {
            get {
                return ResourceManager.GetString("CommunityDepenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the profile to which you want to compare yourself.
        /// </summary>
        public static string CommunityNote {
            get {
                return ResourceManager.GetString("CommunityNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depenses.
        /// </summary>
        public static string Depenses {
            get {
                return ResourceManager.GetString("Depenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can sompare your depenses over different periods with the depenses of other clients of the bank.
        /// </summary>
        public static string DepensesNote {
            get {
                return ResourceManager.GetString("DepensesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depenses Repartition.
        /// </summary>
        public static string DepensesRepartition {
            get {
                return ResourceManager.GetString("DepensesRepartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My depenses.
        /// </summary>
        public static string MyDepenses {
            get {
                return ResourceManager.GetString("MyDepenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My depenses repartition.
        /// </summary>
        public static string MyDepensesRepartition {
            get {
                return ResourceManager.GetString("MyDepensesRepartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not filled in your family status. Only clients which have filled in the status can compare themselves to other clients..
        /// </summary>
        public static string NoRightsToSeeProfiles {
            get {
                return ResourceManager.GetString("NoRightsToSeeProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your depenses.
        /// </summary>
        public static string YourDepenses {
            get {
                return ResourceManager.GetString("YourDepenses", resourceCulture);
            }
        }
    }
}
