//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.Web.Ria.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsPageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPageRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudyBank.Web.Ria.Resources.Pages.SettingsPageRes", typeof(SettingsPageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are your current pictures.
        /// </summary>
        public static string CurrentPictures {
            get {
                return ResourceManager.GetString("CurrentPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of applications which have access to your data..
        /// </summary>
        public static string ListOfTokens {
            get {
                return ResourceManager.GetString("ListOfTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face authentication settings.
        /// </summary>
        public static string ManageImages {
            get {
                return ResourceManager.GetString("ManageImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage images which are used for your face authentication.
        /// </summary>
        public static string ManageImagesMessage {
            get {
                return ResourceManager.GetString("ManageImagesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open data management.
        /// </summary>
        public static string OpenData {
            get {
                return ResourceManager.GetString("OpenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the camera.
        /// </summary>
        public static string StartWebCam {
            get {
                return ResourceManager.GetString("StartWebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can remove the application when you do not want to grant it access to your data anymore..
        /// </summary>
        public static string TokensNote {
            get {
                return ResourceManager.GetString("TokensNote", resourceCulture);
            }
        }
    }
}
