USE [master]
GO

/****** If exists, drop [DATABASE_NAME] ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'DATABASE_NAME')
ALTER DATABASE [DATABASE_NAME]
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
    
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'DATABASE_NAME')
DROP DATABASE [DATABASE_NAME]
GO

USE [master]
GO

/****** Create [DATABASE_NAME] ******/
CREATE DATABASE [DATABASE_NAME]
GO

ALTER DATABASE [DATABASE_NAME] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DATABASE_NAME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

USE [DATABASE_NAME]
GO

IF EXISTS (SELECT * FROM sys.server_principals WHERE name=N'DATABASE_USER')
DROP LOGIN [DATABASE_USER]
GO

CREATE LOGIN [DATABASE_USER] WITH PASSWORD=N'DATABASE_PASSWORD', DEFAULT_DATABASE=[DATABASE_NAME], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF


/****** Create [DATABASE_USER] ******/
CREATE USER [DATABASE_USER] FOR LOGIN [DATABASE_USER] WITH DEFAULT_SCHEMA=[dbo]
GO

USE [DATABASE_NAME]
exec sp_addrolemember 'db_owner', 'DATABASE_USER'
GO
