//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.PortableServices.TagDepenses {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagDepensesDto", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.Dto")]
    public partial class TagDepensesDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal DepensesField;
        
        private int TagIdField;
        
        private string TagNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Depenses {
            get {
                return this.DepensesField;
            }
            set {
                if ((this.DepensesField.Equals(value) != true)) {
                    this.DepensesField = value;
                    this.RaisePropertyChanged("Depenses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TagId {
            get {
                return this.TagIdField;
            }
            set {
                if ((this.TagIdField.Equals(value) != true)) {
                    this.TagIdField = value;
                    this.RaisePropertyChanged("TagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="octo.depenses.service", ConfigurationName="TagDepenses.WCFTagDepensesService")]
    public interface WCFTagDepensesService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.depenses.service/WCFTagDepensesService/GetTagDepensesForProfile", ReplyAction="octo.depenses.service/WCFTagDepensesService/GetTagDepensesForProfileResponse")]
        System.IAsyncResult BeginGetTagDepensesForProfile(int profileId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> EndGetTagDepensesForProfile(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.depenses.service/WCFTagDepensesService/GetTagDepensesForCustomer", ReplyAction="octo.depenses.service/WCFTagDepensesService/GetTagDepensesForCustomerResponse")]
        System.IAsyncResult BeginGetTagDepensesForCustomer(int customerId, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> EndGetTagDepensesForCustomer(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFTagDepensesServiceChannel : CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTagDepensesForProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTagDepensesForProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTagDepensesForCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTagDepensesForCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFTagDepensesServiceClient : System.ServiceModel.ClientBase<CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService>, CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService {
        
        private BeginOperationDelegate onBeginGetTagDepensesForProfileDelegate;
        
        private EndOperationDelegate onEndGetTagDepensesForProfileDelegate;
        
        private System.Threading.SendOrPostCallback onGetTagDepensesForProfileCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTagDepensesForCustomerDelegate;
        
        private EndOperationDelegate onEndGetTagDepensesForCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetTagDepensesForCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFTagDepensesServiceClient() {
        }
        
        public WCFTagDepensesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFTagDepensesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFTagDepensesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFTagDepensesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetTagDepensesForProfileCompletedEventArgs> GetTagDepensesForProfileCompleted;
        
        public event System.EventHandler<GetTagDepensesForCustomerCompletedEventArgs> GetTagDepensesForCustomerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService.BeginGetTagDepensesForProfile(int profileId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTagDepensesForProfile(profileId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService.EndGetTagDepensesForProfile(System.IAsyncResult result) {
            return base.Channel.EndGetTagDepensesForProfile(result);
        }
        
        private System.IAsyncResult OnBeginGetTagDepensesForProfile(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int profileId = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService)(this)).BeginGetTagDepensesForProfile(profileId, callback, asyncState);
        }
        
        private object[] OnEndGetTagDepensesForProfile(System.IAsyncResult result) {
            System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> retVal = ((CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService)(this)).EndGetTagDepensesForProfile(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTagDepensesForProfileCompleted(object state) {
            if ((this.GetTagDepensesForProfileCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTagDepensesForProfileCompleted(this, new GetTagDepensesForProfileCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTagDepensesForProfileAsync(int profileId) {
            this.GetTagDepensesForProfileAsync(profileId, null);
        }
        
        public void GetTagDepensesForProfileAsync(int profileId, object userState) {
            if ((this.onBeginGetTagDepensesForProfileDelegate == null)) {
                this.onBeginGetTagDepensesForProfileDelegate = new BeginOperationDelegate(this.OnBeginGetTagDepensesForProfile);
            }
            if ((this.onEndGetTagDepensesForProfileDelegate == null)) {
                this.onEndGetTagDepensesForProfileDelegate = new EndOperationDelegate(this.OnEndGetTagDepensesForProfile);
            }
            if ((this.onGetTagDepensesForProfileCompletedDelegate == null)) {
                this.onGetTagDepensesForProfileCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTagDepensesForProfileCompleted);
            }
            base.InvokeAsync(this.onBeginGetTagDepensesForProfileDelegate, new object[] {
                        profileId}, this.onEndGetTagDepensesForProfileDelegate, this.onGetTagDepensesForProfileCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService.BeginGetTagDepensesForCustomer(int customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTagDepensesForCustomer(customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService.EndGetTagDepensesForCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetTagDepensesForCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetTagDepensesForCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int customerId = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService)(this)).BeginGetTagDepensesForCustomer(customerId, callback, asyncState);
        }
        
        private object[] OnEndGetTagDepensesForCustomer(System.IAsyncResult result) {
            System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> retVal = ((CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService)(this)).EndGetTagDepensesForCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTagDepensesForCustomerCompleted(object state) {
            if ((this.GetTagDepensesForCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTagDepensesForCustomerCompleted(this, new GetTagDepensesForCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTagDepensesForCustomerAsync(int customerId) {
            this.GetTagDepensesForCustomerAsync(customerId, null);
        }
        
        public void GetTagDepensesForCustomerAsync(int customerId, object userState) {
            if ((this.onBeginGetTagDepensesForCustomerDelegate == null)) {
                this.onBeginGetTagDepensesForCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetTagDepensesForCustomer);
            }
            if ((this.onEndGetTagDepensesForCustomerDelegate == null)) {
                this.onEndGetTagDepensesForCustomerDelegate = new EndOperationDelegate(this.OnEndGetTagDepensesForCustomer);
            }
            if ((this.onGetTagDepensesForCustomerCompletedDelegate == null)) {
                this.onGetTagDepensesForCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTagDepensesForCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetTagDepensesForCustomerDelegate, new object[] {
                        customerId}, this.onEndGetTagDepensesForCustomerDelegate, this.onGetTagDepensesForCustomerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService CreateChannel() {
            return new WCFTagDepensesServiceClientChannel(this);
        }
        
        private class WCFTagDepensesServiceClientChannel : ChannelBase<CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService>, CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService {
            
            public WCFTagDepensesServiceClientChannel(System.ServiceModel.ClientBase<CloudyBank.PortableServices.TagDepenses.WCFTagDepensesService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetTagDepensesForProfile(int profileId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = profileId;
                System.IAsyncResult _result = base.BeginInvoke("GetTagDepensesForProfile", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> EndGetTagDepensesForProfile(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> _result = ((System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto>)(base.EndInvoke("GetTagDepensesForProfile", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTagDepensesForCustomer(int customerId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerId;
                System.IAsyncResult _result = base.BeginInvoke("GetTagDepensesForCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> EndGetTagDepensesForCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto> _result = ((System.Collections.Generic.List<CloudyBank.PortableServices.TagDepenses.TagDepensesDto>)(base.EndInvoke("GetTagDepensesForCustomer", _args, result)));
                return _result;
            }
        }
    }
}
