//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.Web.Ria.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ViewModelsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewModelsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudyBank.Web.Ria.ViewModels.ViewModelsResources", typeof(ViewModelsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered amount was negative.
        /// </summary>
        internal static string AmountNegative {
            get {
                return ResourceManager.GetString("AmountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating bussines partner.
        /// </summary>
        internal static string ErrorCreatingBP {
            get {
                return ResourceManager.GetString("ErrorCreatingBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make transfer within the same account..
        /// </summary>
        internal static string ErrorSameAccounts {
            get {
                return ResourceManager.GetString("ErrorSameAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving business partner.
        /// </summary>
        internal static string ErrorSavingPartner {
            get {
                return ResourceManager.GetString("ErrorSavingPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the payment.
        /// </summary>
        internal static string ErrorSavingPayment {
            get {
                return ResourceManager.GetString("ErrorSavingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving payment event.
        /// </summary>
        internal static string ErrorSavingPaymentEvent {
            get {
                return ResourceManager.GetString("ErrorSavingPaymentEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while tagging the operation.
        /// </summary>
        internal static string ErrorTaggingOperations {
            get {
                return ResourceManager.GetString("ErrorTaggingOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error was made while making the transfer..
        /// </summary>
        internal static string ErrorWhileMakingTransfer {
            get {
                return ResourceManager.GetString("ErrorWhileMakingTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the account from which you want to transfer the money.
        /// </summary>
        internal static string FromAccountNotSet {
            get {
                return ResourceManager.GetString("FromAccountNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not delete the image.
        /// </summary>
        internal static string ImageDeleteIssue {
            get {
                return ResourceManager.GetString("ImageDeleteIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email.
        /// </summary>
        internal static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty..
        /// </summary>
        internal static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No face was found in the image that you took with your web cam.
        /// </summary>
        internal static string NoFaceFound {
            get {
                return ResourceManager.GetString("NoFaceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enought money on the account.
        /// </summary>
        internal static string NotEnoughMoney {
            get {
                return ResourceManager.GetString("NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        internal static string TitleEmpty {
            get {
                return ResourceManager.GetString("TitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction OK, code: {0}.
        /// </summary>
        internal static string TransactionOK {
            get {
                return ResourceManager.GetString("TransactionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security error while making transaction.
        /// </summary>
        internal static string TransactionSecurityError {
            get {
                return ResourceManager.GetString("TransactionSecurityError", resourceCulture);
            }
        }
    }
}
