//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.PortableServices.PaymentEvents {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentEventDto", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.Dto")]
    public partial class PaymentEventDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int AccountIdField;
        
        private decimal AmountField;
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string PartnerIbanField;
        
        private int PartnerIdField;
        
        private string PartnerNameField;
        
        private bool PayedField;
        
        private bool RegularField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerIban {
            get {
                return this.PartnerIbanField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerIbanField, value) != true)) {
                    this.PartnerIbanField = value;
                    this.RaisePropertyChanged("PartnerIban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PartnerId {
            get {
                return this.PartnerIdField;
            }
            set {
                if ((this.PartnerIdField.Equals(value) != true)) {
                    this.PartnerIdField = value;
                    this.RaisePropertyChanged("PartnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerName {
            get {
                return this.PartnerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerNameField, value) != true)) {
                    this.PartnerNameField = value;
                    this.RaisePropertyChanged("PartnerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Payed {
            get {
                return this.PayedField;
            }
            set {
                if ((this.PayedField.Equals(value) != true)) {
                    this.PayedField = value;
                    this.RaisePropertyChanged("Payed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Regular {
            get {
                return this.RegularField;
            }
            set {
                if ((this.RegularField.Equals(value) != true)) {
                    this.RegularField = value;
                    this.RaisePropertyChanged("Regular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="octo.events.service", ConfigurationName="PaymentEvents.WCFPaymentEventService")]
    public interface WCFPaymentEventService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.events.service/WCFPaymentEventService/GetPaymentEventsForCustomer", ReplyAction="octo.events.service/WCFPaymentEventService/GetPaymentEventsForCustomerResponse")]
        System.IAsyncResult BeginGetPaymentEventsForCustomer(int customerID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto> EndGetPaymentEventsForCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.events.service/WCFPaymentEventService/CreatePaymentEvent", ReplyAction="octo.events.service/WCFPaymentEventService/CreatePaymentEventResponse")]
        System.IAsyncResult BeginCreatePaymentEvent(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, int customerId, System.AsyncCallback callback, object asyncState);
        
        int EndCreatePaymentEvent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.events.service/WCFPaymentEventService/GetPaymentEventById", ReplyAction="octo.events.service/WCFPaymentEventService/GetPaymentEventByIdResponse")]
        System.IAsyncResult BeginGetPaymentEventById(int eventId, System.AsyncCallback callback, object asyncState);
        
        CloudyBank.PortableServices.PaymentEvents.PaymentEventDto EndGetPaymentEventById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.events.service/WCFPaymentEventService/RemovePaymentEvent", ReplyAction="octo.events.service/WCFPaymentEventService/RemovePaymentEventResponse")]
        System.IAsyncResult BeginRemovePaymentEvent(int paymentId, System.AsyncCallback callback, object asyncState);
        
        bool EndRemovePaymentEvent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.events.service/WCFPaymentEventService/UpdatePaymentEvent", ReplyAction="octo.events.service/WCFPaymentEventService/UpdatePaymentEventResponse")]
        System.IAsyncResult BeginUpdatePaymentEvent(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdatePaymentEvent(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFPaymentEventServiceChannel : CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentEventsForCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPaymentEventsForCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreatePaymentEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreatePaymentEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPaymentEventByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPaymentEventByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public CloudyBank.PortableServices.PaymentEvents.PaymentEventDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((CloudyBank.PortableServices.PaymentEvents.PaymentEventDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemovePaymentEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemovePaymentEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePaymentEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdatePaymentEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFPaymentEventServiceClient : System.ServiceModel.ClientBase<CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService>, CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService {
        
        private BeginOperationDelegate onBeginGetPaymentEventsForCustomerDelegate;
        
        private EndOperationDelegate onEndGetPaymentEventsForCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetPaymentEventsForCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreatePaymentEventDelegate;
        
        private EndOperationDelegate onEndCreatePaymentEventDelegate;
        
        private System.Threading.SendOrPostCallback onCreatePaymentEventCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPaymentEventByIdDelegate;
        
        private EndOperationDelegate onEndGetPaymentEventByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetPaymentEventByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemovePaymentEventDelegate;
        
        private EndOperationDelegate onEndRemovePaymentEventDelegate;
        
        private System.Threading.SendOrPostCallback onRemovePaymentEventCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePaymentEventDelegate;
        
        private EndOperationDelegate onEndUpdatePaymentEventDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePaymentEventCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFPaymentEventServiceClient() {
        }
        
        public WCFPaymentEventServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFPaymentEventServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFPaymentEventServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFPaymentEventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPaymentEventsForCustomerCompletedEventArgs> GetPaymentEventsForCustomerCompleted;
        
        public event System.EventHandler<CreatePaymentEventCompletedEventArgs> CreatePaymentEventCompleted;
        
        public event System.EventHandler<GetPaymentEventByIdCompletedEventArgs> GetPaymentEventByIdCompleted;
        
        public event System.EventHandler<RemovePaymentEventCompletedEventArgs> RemovePaymentEventCompleted;
        
        public event System.EventHandler<UpdatePaymentEventCompletedEventArgs> UpdatePaymentEventCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.BeginGetPaymentEventsForCustomer(int customerID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentEventsForCustomer(customerID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto> CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.EndGetPaymentEventsForCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentEventsForCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetPaymentEventsForCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int customerID = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).BeginGetPaymentEventsForCustomer(customerID, callback, asyncState);
        }
        
        private object[] OnEndGetPaymentEventsForCustomer(System.IAsyncResult result) {
            System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto> retVal = ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).EndGetPaymentEventsForCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPaymentEventsForCustomerCompleted(object state) {
            if ((this.GetPaymentEventsForCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentEventsForCustomerCompleted(this, new GetPaymentEventsForCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPaymentEventsForCustomerAsync(int customerID) {
            this.GetPaymentEventsForCustomerAsync(customerID, null);
        }
        
        public void GetPaymentEventsForCustomerAsync(int customerID, object userState) {
            if ((this.onBeginGetPaymentEventsForCustomerDelegate == null)) {
                this.onBeginGetPaymentEventsForCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentEventsForCustomer);
            }
            if ((this.onEndGetPaymentEventsForCustomerDelegate == null)) {
                this.onEndGetPaymentEventsForCustomerDelegate = new EndOperationDelegate(this.OnEndGetPaymentEventsForCustomer);
            }
            if ((this.onGetPaymentEventsForCustomerCompletedDelegate == null)) {
                this.onGetPaymentEventsForCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentEventsForCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentEventsForCustomerDelegate, new object[] {
                        customerID}, this.onEndGetPaymentEventsForCustomerDelegate, this.onGetPaymentEventsForCustomerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.BeginCreatePaymentEvent(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, int customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreatePaymentEvent(paymentDto, customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.EndCreatePaymentEvent(System.IAsyncResult result) {
            return base.Channel.EndCreatePaymentEvent(result);
        }
        
        private System.IAsyncResult OnBeginCreatePaymentEvent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto = ((CloudyBank.PortableServices.PaymentEvents.PaymentEventDto)(inValues[0]));
            int customerId = ((int)(inValues[1]));
            return ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).BeginCreatePaymentEvent(paymentDto, customerId, callback, asyncState);
        }
        
        private object[] OnEndCreatePaymentEvent(System.IAsyncResult result) {
            int retVal = ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).EndCreatePaymentEvent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreatePaymentEventCompleted(object state) {
            if ((this.CreatePaymentEventCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreatePaymentEventCompleted(this, new CreatePaymentEventCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreatePaymentEventAsync(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, int customerId) {
            this.CreatePaymentEventAsync(paymentDto, customerId, null);
        }
        
        public void CreatePaymentEventAsync(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, int customerId, object userState) {
            if ((this.onBeginCreatePaymentEventDelegate == null)) {
                this.onBeginCreatePaymentEventDelegate = new BeginOperationDelegate(this.OnBeginCreatePaymentEvent);
            }
            if ((this.onEndCreatePaymentEventDelegate == null)) {
                this.onEndCreatePaymentEventDelegate = new EndOperationDelegate(this.OnEndCreatePaymentEvent);
            }
            if ((this.onCreatePaymentEventCompletedDelegate == null)) {
                this.onCreatePaymentEventCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreatePaymentEventCompleted);
            }
            base.InvokeAsync(this.onBeginCreatePaymentEventDelegate, new object[] {
                        paymentDto,
                        customerId}, this.onEndCreatePaymentEventDelegate, this.onCreatePaymentEventCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.BeginGetPaymentEventById(int eventId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPaymentEventById(eventId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudyBank.PortableServices.PaymentEvents.PaymentEventDto CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.EndGetPaymentEventById(System.IAsyncResult result) {
            return base.Channel.EndGetPaymentEventById(result);
        }
        
        private System.IAsyncResult OnBeginGetPaymentEventById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int eventId = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).BeginGetPaymentEventById(eventId, callback, asyncState);
        }
        
        private object[] OnEndGetPaymentEventById(System.IAsyncResult result) {
            CloudyBank.PortableServices.PaymentEvents.PaymentEventDto retVal = ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).EndGetPaymentEventById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPaymentEventByIdCompleted(object state) {
            if ((this.GetPaymentEventByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPaymentEventByIdCompleted(this, new GetPaymentEventByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPaymentEventByIdAsync(int eventId) {
            this.GetPaymentEventByIdAsync(eventId, null);
        }
        
        public void GetPaymentEventByIdAsync(int eventId, object userState) {
            if ((this.onBeginGetPaymentEventByIdDelegate == null)) {
                this.onBeginGetPaymentEventByIdDelegate = new BeginOperationDelegate(this.OnBeginGetPaymentEventById);
            }
            if ((this.onEndGetPaymentEventByIdDelegate == null)) {
                this.onEndGetPaymentEventByIdDelegate = new EndOperationDelegate(this.OnEndGetPaymentEventById);
            }
            if ((this.onGetPaymentEventByIdCompletedDelegate == null)) {
                this.onGetPaymentEventByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPaymentEventByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetPaymentEventByIdDelegate, new object[] {
                        eventId}, this.onEndGetPaymentEventByIdDelegate, this.onGetPaymentEventByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.BeginRemovePaymentEvent(int paymentId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemovePaymentEvent(paymentId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.EndRemovePaymentEvent(System.IAsyncResult result) {
            return base.Channel.EndRemovePaymentEvent(result);
        }
        
        private System.IAsyncResult OnBeginRemovePaymentEvent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int paymentId = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).BeginRemovePaymentEvent(paymentId, callback, asyncState);
        }
        
        private object[] OnEndRemovePaymentEvent(System.IAsyncResult result) {
            bool retVal = ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).EndRemovePaymentEvent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemovePaymentEventCompleted(object state) {
            if ((this.RemovePaymentEventCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemovePaymentEventCompleted(this, new RemovePaymentEventCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemovePaymentEventAsync(int paymentId) {
            this.RemovePaymentEventAsync(paymentId, null);
        }
        
        public void RemovePaymentEventAsync(int paymentId, object userState) {
            if ((this.onBeginRemovePaymentEventDelegate == null)) {
                this.onBeginRemovePaymentEventDelegate = new BeginOperationDelegate(this.OnBeginRemovePaymentEvent);
            }
            if ((this.onEndRemovePaymentEventDelegate == null)) {
                this.onEndRemovePaymentEventDelegate = new EndOperationDelegate(this.OnEndRemovePaymentEvent);
            }
            if ((this.onRemovePaymentEventCompletedDelegate == null)) {
                this.onRemovePaymentEventCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemovePaymentEventCompleted);
            }
            base.InvokeAsync(this.onBeginRemovePaymentEventDelegate, new object[] {
                        paymentId}, this.onEndRemovePaymentEventDelegate, this.onRemovePaymentEventCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.BeginUpdatePaymentEvent(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePaymentEvent(paymentDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService.EndUpdatePaymentEvent(System.IAsyncResult result) {
            return base.Channel.EndUpdatePaymentEvent(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePaymentEvent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto = ((CloudyBank.PortableServices.PaymentEvents.PaymentEventDto)(inValues[0]));
            return ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).BeginUpdatePaymentEvent(paymentDto, callback, asyncState);
        }
        
        private object[] OnEndUpdatePaymentEvent(System.IAsyncResult result) {
            bool retVal = ((CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService)(this)).EndUpdatePaymentEvent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdatePaymentEventCompleted(object state) {
            if ((this.UpdatePaymentEventCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePaymentEventCompleted(this, new UpdatePaymentEventCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePaymentEventAsync(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto) {
            this.UpdatePaymentEventAsync(paymentDto, null);
        }
        
        public void UpdatePaymentEventAsync(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, object userState) {
            if ((this.onBeginUpdatePaymentEventDelegate == null)) {
                this.onBeginUpdatePaymentEventDelegate = new BeginOperationDelegate(this.OnBeginUpdatePaymentEvent);
            }
            if ((this.onEndUpdatePaymentEventDelegate == null)) {
                this.onEndUpdatePaymentEventDelegate = new EndOperationDelegate(this.OnEndUpdatePaymentEvent);
            }
            if ((this.onUpdatePaymentEventCompletedDelegate == null)) {
                this.onUpdatePaymentEventCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePaymentEventCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePaymentEventDelegate, new object[] {
                        paymentDto}, this.onEndUpdatePaymentEventDelegate, this.onUpdatePaymentEventCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService CreateChannel() {
            return new WCFPaymentEventServiceClientChannel(this);
        }
        
        private class WCFPaymentEventServiceClientChannel : ChannelBase<CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService>, CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService {
            
            public WCFPaymentEventServiceClientChannel(System.ServiceModel.ClientBase<CloudyBank.PortableServices.PaymentEvents.WCFPaymentEventService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPaymentEventsForCustomer(int customerID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerID;
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentEventsForCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto> EndGetPaymentEventsForCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto> _result = ((System.Collections.Generic.List<CloudyBank.PortableServices.PaymentEvents.PaymentEventDto>)(base.EndInvoke("GetPaymentEventsForCustomer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreatePaymentEvent(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, int customerId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = paymentDto;
                _args[1] = customerId;
                System.IAsyncResult _result = base.BeginInvoke("CreatePaymentEvent", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreatePaymentEvent(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreatePaymentEvent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPaymentEventById(int eventId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = eventId;
                System.IAsyncResult _result = base.BeginInvoke("GetPaymentEventById", _args, callback, asyncState);
                return _result;
            }
            
            public CloudyBank.PortableServices.PaymentEvents.PaymentEventDto EndGetPaymentEventById(System.IAsyncResult result) {
                object[] _args = new object[0];
                CloudyBank.PortableServices.PaymentEvents.PaymentEventDto _result = ((CloudyBank.PortableServices.PaymentEvents.PaymentEventDto)(base.EndInvoke("GetPaymentEventById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRemovePaymentEvent(int paymentId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = paymentId;
                System.IAsyncResult _result = base.BeginInvoke("RemovePaymentEvent", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndRemovePaymentEvent(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("RemovePaymentEvent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdatePaymentEvent(CloudyBank.PortableServices.PaymentEvents.PaymentEventDto paymentDto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = paymentDto;
                System.IAsyncResult _result = base.BeginInvoke("UpdatePaymentEvent", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndUpdatePaymentEvent(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("UpdatePaymentEvent", _args, result)));
                return _result;
            }
        }
    }
}
