//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudyBank.PortableServices.Partners {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessPartnerDto", Namespace="http://schemas.datacontract.org/2004/07/CloudyBank.Dto")]
    public partial class BusinessPartnerDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CustomerIdField;
        
        private string DescriptionField;
        
        private string IbanField;
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="octo.partners.service", ConfigurationName="Partners.WCFPartnerService")]
    public interface WCFPartnerService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.partners.service/WCFPartnerService/GetPartnersForCustomer", ReplyAction="octo.partners.service/WCFPartnerService/GetPartnersForCustomerResponse")]
        System.IAsyncResult BeginGetPartnersForCustomer(int customerID, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto> EndGetPartnersForCustomer(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.partners.service/WCFPartnerService/CreatePartner", ReplyAction="octo.partners.service/WCFPartnerService/CreatePartnerResponse")]
        System.IAsyncResult BeginCreatePartner(CloudyBank.PortableServices.Partners.BusinessPartnerDto partnerDto, int customerId, System.AsyncCallback callback, object asyncState);
        
        int EndCreatePartner(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.partners.service/WCFPartnerService/UpdatePartner", ReplyAction="octo.partners.service/WCFPartnerService/UpdatePartnerResponse")]
        System.IAsyncResult BeginUpdatePartner(CloudyBank.PortableServices.Partners.BusinessPartnerDto partner, int customerId, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdatePartner(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="octo.partners.service/WCFPartnerService/RemovePartner", ReplyAction="octo.partners.service/WCFPartnerService/RemovePartnerResponse")]
        System.IAsyncResult BeginRemovePartner(int partnerId, int customerId, System.AsyncCallback callback, object asyncState);
        
        bool EndRemovePartner(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WCFPartnerServiceChannel : CloudyBank.PortableServices.Partners.WCFPartnerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPartnersForCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPartnersForCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreatePartnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreatePartnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePartnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdatePartnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemovePartnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemovePartnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFPartnerServiceClient : System.ServiceModel.ClientBase<CloudyBank.PortableServices.Partners.WCFPartnerService>, CloudyBank.PortableServices.Partners.WCFPartnerService {
        
        private BeginOperationDelegate onBeginGetPartnersForCustomerDelegate;
        
        private EndOperationDelegate onEndGetPartnersForCustomerDelegate;
        
        private System.Threading.SendOrPostCallback onGetPartnersForCustomerCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreatePartnerDelegate;
        
        private EndOperationDelegate onEndCreatePartnerDelegate;
        
        private System.Threading.SendOrPostCallback onCreatePartnerCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdatePartnerDelegate;
        
        private EndOperationDelegate onEndUpdatePartnerDelegate;
        
        private System.Threading.SendOrPostCallback onUpdatePartnerCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemovePartnerDelegate;
        
        private EndOperationDelegate onEndRemovePartnerDelegate;
        
        private System.Threading.SendOrPostCallback onRemovePartnerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WCFPartnerServiceClient() {
        }
        
        public WCFPartnerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFPartnerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFPartnerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFPartnerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPartnersForCustomerCompletedEventArgs> GetPartnersForCustomerCompleted;
        
        public event System.EventHandler<CreatePartnerCompletedEventArgs> CreatePartnerCompleted;
        
        public event System.EventHandler<UpdatePartnerCompletedEventArgs> UpdatePartnerCompleted;
        
        public event System.EventHandler<RemovePartnerCompletedEventArgs> RemovePartnerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Partners.WCFPartnerService.BeginGetPartnersForCustomer(int customerID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPartnersForCustomer(customerID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto> CloudyBank.PortableServices.Partners.WCFPartnerService.EndGetPartnersForCustomer(System.IAsyncResult result) {
            return base.Channel.EndGetPartnersForCustomer(result);
        }
        
        private System.IAsyncResult OnBeginGetPartnersForCustomer(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int customerID = ((int)(inValues[0]));
            return ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).BeginGetPartnersForCustomer(customerID, callback, asyncState);
        }
        
        private object[] OnEndGetPartnersForCustomer(System.IAsyncResult result) {
            System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto> retVal = ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).EndGetPartnersForCustomer(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPartnersForCustomerCompleted(object state) {
            if ((this.GetPartnersForCustomerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPartnersForCustomerCompleted(this, new GetPartnersForCustomerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPartnersForCustomerAsync(int customerID) {
            this.GetPartnersForCustomerAsync(customerID, null);
        }
        
        public void GetPartnersForCustomerAsync(int customerID, object userState) {
            if ((this.onBeginGetPartnersForCustomerDelegate == null)) {
                this.onBeginGetPartnersForCustomerDelegate = new BeginOperationDelegate(this.OnBeginGetPartnersForCustomer);
            }
            if ((this.onEndGetPartnersForCustomerDelegate == null)) {
                this.onEndGetPartnersForCustomerDelegate = new EndOperationDelegate(this.OnEndGetPartnersForCustomer);
            }
            if ((this.onGetPartnersForCustomerCompletedDelegate == null)) {
                this.onGetPartnersForCustomerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPartnersForCustomerCompleted);
            }
            base.InvokeAsync(this.onBeginGetPartnersForCustomerDelegate, new object[] {
                        customerID}, this.onEndGetPartnersForCustomerDelegate, this.onGetPartnersForCustomerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Partners.WCFPartnerService.BeginCreatePartner(CloudyBank.PortableServices.Partners.BusinessPartnerDto partnerDto, int customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreatePartner(partnerDto, customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int CloudyBank.PortableServices.Partners.WCFPartnerService.EndCreatePartner(System.IAsyncResult result) {
            return base.Channel.EndCreatePartner(result);
        }
        
        private System.IAsyncResult OnBeginCreatePartner(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CloudyBank.PortableServices.Partners.BusinessPartnerDto partnerDto = ((CloudyBank.PortableServices.Partners.BusinessPartnerDto)(inValues[0]));
            int customerId = ((int)(inValues[1]));
            return ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).BeginCreatePartner(partnerDto, customerId, callback, asyncState);
        }
        
        private object[] OnEndCreatePartner(System.IAsyncResult result) {
            int retVal = ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).EndCreatePartner(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreatePartnerCompleted(object state) {
            if ((this.CreatePartnerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreatePartnerCompleted(this, new CreatePartnerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreatePartnerAsync(CloudyBank.PortableServices.Partners.BusinessPartnerDto partnerDto, int customerId) {
            this.CreatePartnerAsync(partnerDto, customerId, null);
        }
        
        public void CreatePartnerAsync(CloudyBank.PortableServices.Partners.BusinessPartnerDto partnerDto, int customerId, object userState) {
            if ((this.onBeginCreatePartnerDelegate == null)) {
                this.onBeginCreatePartnerDelegate = new BeginOperationDelegate(this.OnBeginCreatePartner);
            }
            if ((this.onEndCreatePartnerDelegate == null)) {
                this.onEndCreatePartnerDelegate = new EndOperationDelegate(this.OnEndCreatePartner);
            }
            if ((this.onCreatePartnerCompletedDelegate == null)) {
                this.onCreatePartnerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreatePartnerCompleted);
            }
            base.InvokeAsync(this.onBeginCreatePartnerDelegate, new object[] {
                        partnerDto,
                        customerId}, this.onEndCreatePartnerDelegate, this.onCreatePartnerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Partners.WCFPartnerService.BeginUpdatePartner(CloudyBank.PortableServices.Partners.BusinessPartnerDto partner, int customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdatePartner(partner, customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool CloudyBank.PortableServices.Partners.WCFPartnerService.EndUpdatePartner(System.IAsyncResult result) {
            return base.Channel.EndUpdatePartner(result);
        }
        
        private System.IAsyncResult OnBeginUpdatePartner(object[] inValues, System.AsyncCallback callback, object asyncState) {
            CloudyBank.PortableServices.Partners.BusinessPartnerDto partner = ((CloudyBank.PortableServices.Partners.BusinessPartnerDto)(inValues[0]));
            int customerId = ((int)(inValues[1]));
            return ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).BeginUpdatePartner(partner, customerId, callback, asyncState);
        }
        
        private object[] OnEndUpdatePartner(System.IAsyncResult result) {
            bool retVal = ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).EndUpdatePartner(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdatePartnerCompleted(object state) {
            if ((this.UpdatePartnerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdatePartnerCompleted(this, new UpdatePartnerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdatePartnerAsync(CloudyBank.PortableServices.Partners.BusinessPartnerDto partner, int customerId) {
            this.UpdatePartnerAsync(partner, customerId, null);
        }
        
        public void UpdatePartnerAsync(CloudyBank.PortableServices.Partners.BusinessPartnerDto partner, int customerId, object userState) {
            if ((this.onBeginUpdatePartnerDelegate == null)) {
                this.onBeginUpdatePartnerDelegate = new BeginOperationDelegate(this.OnBeginUpdatePartner);
            }
            if ((this.onEndUpdatePartnerDelegate == null)) {
                this.onEndUpdatePartnerDelegate = new EndOperationDelegate(this.OnEndUpdatePartner);
            }
            if ((this.onUpdatePartnerCompletedDelegate == null)) {
                this.onUpdatePartnerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdatePartnerCompleted);
            }
            base.InvokeAsync(this.onBeginUpdatePartnerDelegate, new object[] {
                        partner,
                        customerId}, this.onEndUpdatePartnerDelegate, this.onUpdatePartnerCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult CloudyBank.PortableServices.Partners.WCFPartnerService.BeginRemovePartner(int partnerId, int customerId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemovePartner(partnerId, customerId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool CloudyBank.PortableServices.Partners.WCFPartnerService.EndRemovePartner(System.IAsyncResult result) {
            return base.Channel.EndRemovePartner(result);
        }
        
        private System.IAsyncResult OnBeginRemovePartner(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int partnerId = ((int)(inValues[0]));
            int customerId = ((int)(inValues[1]));
            return ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).BeginRemovePartner(partnerId, customerId, callback, asyncState);
        }
        
        private object[] OnEndRemovePartner(System.IAsyncResult result) {
            bool retVal = ((CloudyBank.PortableServices.Partners.WCFPartnerService)(this)).EndRemovePartner(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemovePartnerCompleted(object state) {
            if ((this.RemovePartnerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemovePartnerCompleted(this, new RemovePartnerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemovePartnerAsync(int partnerId, int customerId) {
            this.RemovePartnerAsync(partnerId, customerId, null);
        }
        
        public void RemovePartnerAsync(int partnerId, int customerId, object userState) {
            if ((this.onBeginRemovePartnerDelegate == null)) {
                this.onBeginRemovePartnerDelegate = new BeginOperationDelegate(this.OnBeginRemovePartner);
            }
            if ((this.onEndRemovePartnerDelegate == null)) {
                this.onEndRemovePartnerDelegate = new EndOperationDelegate(this.OnEndRemovePartner);
            }
            if ((this.onRemovePartnerCompletedDelegate == null)) {
                this.onRemovePartnerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemovePartnerCompleted);
            }
            base.InvokeAsync(this.onBeginRemovePartnerDelegate, new object[] {
                        partnerId,
                        customerId}, this.onEndRemovePartnerDelegate, this.onRemovePartnerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override CloudyBank.PortableServices.Partners.WCFPartnerService CreateChannel() {
            return new WCFPartnerServiceClientChannel(this);
        }
        
        private class WCFPartnerServiceClientChannel : ChannelBase<CloudyBank.PortableServices.Partners.WCFPartnerService>, CloudyBank.PortableServices.Partners.WCFPartnerService {
            
            public WCFPartnerServiceClientChannel(System.ServiceModel.ClientBase<CloudyBank.PortableServices.Partners.WCFPartnerService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPartnersForCustomer(int customerID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = customerID;
                System.IAsyncResult _result = base.BeginInvoke("GetPartnersForCustomer", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto> EndGetPartnersForCustomer(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto> _result = ((System.Collections.Generic.List<CloudyBank.PortableServices.Partners.BusinessPartnerDto>)(base.EndInvoke("GetPartnersForCustomer", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreatePartner(CloudyBank.PortableServices.Partners.BusinessPartnerDto partnerDto, int customerId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = partnerDto;
                _args[1] = customerId;
                System.IAsyncResult _result = base.BeginInvoke("CreatePartner", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCreatePartner(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CreatePartner", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdatePartner(CloudyBank.PortableServices.Partners.BusinessPartnerDto partner, int customerId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = partner;
                _args[1] = customerId;
                System.IAsyncResult _result = base.BeginInvoke("UpdatePartner", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndUpdatePartner(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("UpdatePartner", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRemovePartner(int partnerId, int customerId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = partnerId;
                _args[1] = customerId;
                System.IAsyncResult _result = base.BeginInvoke("RemovePartner", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndRemovePartner(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("RemovePartner", _args, result)));
                return _result;
            }
        }
    }
}
